### ISSUE TITLE
Build with vue 3.2.34

### ISSUE THREAD

**Issue by KaelWD** [vueuse/head#66]
vuejs/core#5416 added two new arguments to the `DefineComponent` type, causing the emitted type from earlier versions to throw 

```
node_modules/@vueuse/head/dist/index.d.ts:45:149 - error TS2344: Type 'VNodeProps & AllowedComponentProps & ComponentCustomProps' does not satisfy the constraint 'ComponentProvideOptions'.
  Type 'VNodeProps & AllowedComponentProps & ComponentCustomProps' is not assignable to type 'ObjectProvideOptions'.
    Index signature for type 'string' is missing in type 'VNodeProps & AllowedComponentProps & ComponentCustomProps'.

45 declare const Head: vue.DefineComponent<{}, () => null, {}, {}, {}, vue.ComponentOptionsMixin, vue.ComponentOptionsMixin, vue.EmitsOptions, string, vue.VNodeProps & vue.AllowedComponentProps & vue.ComponentCustomProps, Readonly<vue.ExtractPropTypes<{}>>, {}>;
                                                                                                                                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by KaelWD** [comment]
Fixed upstream by https://github.com/vuejs/core/commit/8071ef47b5adcd5fcd9d0d2ea2cefff5c34ce095
